### ISSUE TITLE
Use hx:* Thymeleaf dialect?

### ISSUE THREAD

**Issue by wimdeblauwe** [spring-petclinic/spring-petclinic-htmx#6]
I see a lot of  `th:attr` usage (e.g `th:attr="hx-get=@{${url} + '?page=' + ${page}}"` ) that could be replaced with `hx:get="@{${url} + '?page=' + ${page}}"`, since the htmx-spring-boot-thymeleaf library is already present in the project.

In this particual example, it could be simplified further to: `hx:get="@{${url}(page=${page})}"`

I could create a PR for this if you are interested in this change.

**Comment by agrison** [comment]
Sure that would be great!
